favorite:
  name: Favorite position
  description: Moves the blind to the favorite position.
  fields:
    entity_id:
      name: Entity
      description: Name of the entity_id to move to the favorite position.
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble
connect:
  name: Connect
  description: Connects to the blind, if already connected it updates the disconnect timer.
  fields:
    entity_id:
      name: Entity
      description: Name of the entity_id to connect to.
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble
    timeout:
      name: Disconnect time
      description: The time in seconds after which Home Assistant will terminate the connection to the device.
      required: false
      default: 15
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
disconnect:
  name: Disconnect
  description: Terminates the connection to the blind, or stops connecting.
  fields:
    entity_id:
      name: Entity
      description: Name of the entity_id to terminate the connection with.
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble
status:
  name: Status information
  description: Gets the position, tilt and battery percentage information from the motor.
  fields:
    entity_id:
      name: Entity
      description: Name of the entity_id to get status information from.
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble