connect:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble
    timeout:
      required: false
      default: 15
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
disconnect:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble
favorite:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble
status:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover
          integration: motionblinds_ble